### PR TITLE
Add MSVC2017 build config and project

### LINKED ISSUE #24: Broken compilation under MSVC 2017
6b68f4df034606d2f243733469f0f6177994bb96 deleted the `config.py` files, which are necessary for running scons under Windows.
I extracted them manually from the GitHub commit. However, compiling Mitsuba with `/O2` (`config-win64-msvc.py`) errors out with: `Scale factors in the camera-to-world transformation are not allowed!`. I narrowed it down to the `/Ob2` flag; swapping `/O2` for `/Oi /Ot /Oy /Ob1 /Gs /GF /Gy` does the trick.

I'm using MSVC 2017, version 15.0.26730.12. Tested scenes are Hair Ball, Hair Curls and Material Test ball from Benedikt Bitterli: http://benedikt-bitterli.me/resources/.

### PR DESCRIPTION
**Pull request by amyspark**
I've recreated the VS project files from scratch. The new VS solution allows Mitsuba to be debugged from within VS. I've also edited the SCons configuration to work around the MSVC `/Ob2` issue.
There are also some errors left wrt. template visibility in `ply_parser.cpp`. Those are confirmed MSVC bugs (see e.g. https://developercommunity.visualstudio.com/content/problem/70100/spurious-compiler-error-complaining-about-nested-t.html).

This pull request fixes #24.

### CODE REVIEW

**Comment by wjakob** [comment]
Ouch -- I had actually made ``config-*`` files for MSVC 2017 and then forgot to commit them :(. I just did that now.

How did you generate the project files? Using ``./data/windows/genproj.py``?

**Comment by amyspark** [comment]
> How did you generate the project files? Using ./data/windows/genproj.py?

Whoops. No, I had created them by hand-- recreating the solution in Visual Studio, copy-pasting configuration, etc. I'll update the script instead.

In the meanwhile, I've rebased the SCons configuration patch on top of your files.

**Comment by amyspark** [comment]
@wjakob , this should be ready now :+1:

**Comment by wjakob** [comment]
Perfect -- this looks great, thank you!

**Pull request merged**
