### PR TITLE
Add Dscalar operator*=(DScalar1&); fix issues 3

### PR DESCRIPTION
**Pull request by cdonovick**
Fix issue #3 reported by @tmccal2 with solution suggested by @BachiLi

### CODE REVIEW

**Comment by wjakob** [comment]
Looks great, but the indentation is wrong -- I think you used spaces instead of tabs (which is what the Mitsuba v1 codebase uses).

**Comment by cdonovick** [comment]
Sorry about that, the indentation is should be correct now

**Comment by wjakob** [comment]
Thanks!

**Comment by lei9wang** [comment]
@wjakob,
could you give a guide about this issue
https://github.com/mitsuba-renderer/mitsuba/issues/88

**Pull request merged**
