### PR TITLE
Mitsuba PDF manual fixes

### LINKED ISSUE #23: PDF manual compilation issues
Compiling the user manual with `gendoc.py` and TeX Live 2017 does not work. I've found the following bugs:

* `main.tex` uses `DIV11`, which is deprecated.
* `main.tex` also uses the ACM bibtex style, which no longer works because it uses old font commands.
* There seems to be two missing images, `bumpy_sphere.jpg` and `bunny_single.jpg`.
* The `singlescatter` plugin docs have a missing reference: `Holzschuch2015`.
* The `normalmap` plugin docs refer to a `bump` plugin. Perhaps `bumpmap` was meant?

### PR DESCRIPTION
**Pull request by amyspark**
- [x] Changed bibliography package to biblatex (ACM bibtex is no longer
supported)
- [x] Added `bumpy_sphere`
- [x] ~~Added `bunny_single`~~
 - ~~requested scene from Nicolas Holzschuch. Once I've received I'll update the pull request~~
 - Material does not seem to work. I've deleted it instead
- [x] Added the missing Holzschuch cite
- [x] Fixed a plugin ref in normalmap
- [x] PDF requires two more runs of pdflatex after bibtex

This pull request (once finished) fixes #23.

### CODE REVIEW

**Comment by wjakob** [comment]
Interesting -- I don't have that file anywhere on my computer (``bunny_single``). If Nicolas does not have it anymore, I propose that we delete it from the documentation.

PS: Thank you for your help with this -- it is much-appreciated!

**Comment by amyspark** [comment]
I've just got a copy from Dr. Holzschuch along with the instructions for compiling it. Once I get the Buddha's material to work, I'll update this.

**Comment by qnzhou** [comment]
Thanks @amyspark .  Just to add to the list, the compiling instructions are out of date.  The mercurial repo (https://www.mitsuba-renderer.org/hg/mitsub) seems to be no longer working.

**Comment by amyspark** [comment]
I can't seem to get this material to work, so I'll go with deleting the image reference.

**Comment by wjakob** [comment]
This PR looks fantastic -- thank you very much for updating the documentation. Please let me know when it's ready to merge, and I will do so right away.

**Comment by amyspark** [comment]
Thanks for the comments! This is ready to merge.

**Comment by wjakob** [comment]
Great -- done! Thank you very much.

**Pull request merged**
